name: Update Dodgers standings

on:
  schedule:
    # Runs at 4 AM and 3 PM PST (12 PM and 11 PM UTC during Standard Time; 11 AM and 10 PM UTC during Daylight Time)
    - cron: '0 12,23 * * *' # Adjusted for UTC-8 (Standard Time)
  workflow_dispatch:

jobs:
  update_standings:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Set up AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.HAEKEO_AWS_KEY }}
        aws-secret-access-key: ${{ secrets.HAEKEO_AWS_SECRET }}
        aws-region: us-west-1
        
    - name: Install dependencies
      run: |
      run: |
        python -m pip install --upgrade pip
        pip install pandas==1.2.3 pyarrow==4.0.1 fastparquet==0.6.3 lxml==4.6.3 requests==2.25.1 beautifulsoup4==4.9.3 boto3==1.17.44 altair_saver==0.5.0 altair-stiles vl-convert-python
    
    - name: Run script
      env:
        AWS_PERSONAL_PROFILE: ${{ secrets.AWS_PERSONAL_PROFILE }}
        AWS_ACCESS_KEY_ID: ${{ secrets.HAEKEO_AWS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.HAEKEO_AWS_SECRET }}
      run: |
        python 00_fetch_standings.py && 
        python 01_create_standings_viz.py && 
        python 02_fetch_batting_data.py && 
        python 03_viz_team_batting_statistics.py

    - name: Configure Git
      run: |
        git config --global user.name 'Matt Stiles'
        git config --global user.email 'haekeostiles@gmail.com'
    
    - name: Commit updated files
      id: commit
      run: |
        set -e
        git add data/processed/*
        git diff --staged --quiet || git commit -m "Automated update of Dodgers standings data"
        echo "::set-output name=result::success"
      continue-on-error: true
        
    - name: Push changes
      if: steps.commit.outputs.result == 'success'
      run: git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
