name: run_dodgers

on:
  schedule:
    - cron: '0 7,11,16,22 * * *'  # Adjusted for UTC (Daylight Saving Time)
  workflow_dispatch:

jobs:
  update_standings:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{github.workspace}}  # This sets the working directory for all run commands
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Set up AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-1

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas pyarrow fastparquet lxml requests beautifulsoup4 boto3 altair_saver altair-stiles vl-convert-python
    
    - name: Create necessary directories
      run: mkdir -p data/pitching
    
    - name: Install Fonts
      run: |
        sudo apt-get update
        sudo apt-get install -y fonts-roboto

    - name: Run scripts
      run: |
        python scripts/01_fetch_process_standings.py
        python scripts/02_fetch_process_batting.py
        python scripts/03_viz_standings.py
        python scripts/04_viz_batting.py
        python scripts/05_fetch_process_pitching.py
        python scripts/06_create_toplines_summary.py
        python scripts/07_fetch_process_season_outcomes.py
        python scripts/08_fetch_process_wins_losses_current.py

    - name: Build Jekyll site
      run: bundle exec jekyll build

    - name: Check for changes
      id: changes
      run: |
          git add .
          git diff --staged --quiet || echo "::set-output name=changes::true"
  
    - name: Commit updated files
      if: steps.changes.outputs.changes == 'true'
      run: |
        git config --global user.name 'Matt Stiles'
        git config --global user.email 'haekeostiles@gmail.com'
        git commit -m "Automated update of Dodgers data, visuals"
  
    - name: Push changes
      if: steps.changes.outputs.changes == 'true'
      run: |
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}