name: run_dodgers

on:
  schedule:
    - cron: '0 8,12,15,23 * 3-10 *'
  workflow_dispatch:

jobs:
  update_and_deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{github.workspace}}  # This sets the working directory for all run commands
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Set up AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-1

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytz pandas geopandas pyarrow fastparquet lxml requests beautifulsoup4 boto3 altair_saver altair-stiles vl-convert-python
    
    - name: Create necessary directories
      run: |
        mkdir -p data/pitching
        mkdir -p data/batting

    - name: Install Fonts
      run: |
        sudo apt-get update
        sudo apt-get install -y fonts-roboto

    - name: Set up Ruby for Jekyll
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0' # Match the version to your Gemfile or latest stable release

    - name: Install Bundler and Jekyll dependencies
      run: |
        gem install bundler
        bundle install

    - name: Run scripts
      run: |
        python scripts/00_fetch_league_standings.py
        python scripts/00_scrape_league_ranks.py
        python scripts/01_fetch_process_standings.py
        python scripts/02_fetch_process_batting.py
        # python scripts/03_viz_standings.py
        # python scripts/04_viz_batting.py
        python scripts/05_fetch_process_pitching.py
        python scripts/06_create_toplines_summary.py
        python scripts/07_fetch_process_season_outcomes.py
        python scripts/08_fetch_process_wins_losses_current.py
        python scripts/09_fetch_process_historic_batting_gamelogs.py
        python scripts/10_fetch_process_attendance.py
        python scripts/11_fetch_process_historic_pitching_gamelogs.py
        python scripts/12_fetch_process_schedule.py
        python scripts/14_fetch_process_batting_mlb.py
        python scripts/15_fetch_xwoba.py
        python scripts/16_fetch_shohei.py
        python scripts/18_generate_projection.py
        python scripts/19_fetch_roster.py

    - name: Build Jekyll site
      run: bundle exec jekyll build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site  # The output folder of Jekyll build
        publish_branch: gh-pages  

    - name: Check for changes
      id: changes
      run: |
        git add .
        git diff --staged --quiet || echo "::set-output name=changes::true"
  
    - name: Commit updated files
      if: steps.changes.outputs.changes == 'true'
      run: |
        git config --global user.name 'Matt Stiles'
        git config --global user.email 'haekeostiles@gmail.com'
        git commit -m "Automated update of Dodgers data, visuals"
  
    - name: Push changes
      if: steps.changes.outputs.changes == 'true'
      run: git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
