name: Post News Roundup

on:
  schedule:
    # Runs hourly, but will only proceed at 1 PM PT.
    - cron: '0 20-21 * * *'
  workflow_dispatch:

jobs:
  post_news:
    runs-on: ubuntu-latest
    steps:
      - name: Check Time in Los Angeles
        id: time_check
        run: |
          if [[ $(TZ="America/Los_Angeles" date +'%H') -eq 13 ]]; then
            echo "Proceeding, it is 1 PM PT."
            echo "proceed=true" >> $GITHUB_OUTPUT
          else
            echo "Stopping, it is not 1 PM PT."
            echo "proceed=false" >> $GITHUB_OUTPUT
          fi

      - uses: actions/checkout@v2
        if: steps.time_check.outputs.proceed == 'true'

      - name: Set up Python
        if: steps.time_check.outputs.proceed == 'true'
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Set up AWS Credentials
        if: steps.time_check.outputs.proceed == 'true'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      - name: Install dependencies
        if: steps.time_check.outputs.proceed == 'true'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run news fetch and tweet
        if: steps.time_check.outputs.proceed == 'true'
        env:
          DODGERS_TWITTER_API_KEY: ${{ secrets.DODGERS_TWITTER_API_KEY }}
          DODGERS_TWITTER_API_SECRET: ${{ secrets.DODGERS_TWITTER_API_SECRET }}
          DODGERS_TWITTER_ACCESS_TOKEN: ${{ secrets.DODGERS_TWITTER_ACCESS_TOKEN }}
          DODGERS_TWITTER_ACCESS_SECRET: ${{ secrets.DODGERS_TWITTER_API_ACCESS_SECRET }}
        run: python scripts/24_fetch_news.py --post-tweet 