name: Post News Roundup

on:
  schedule:
    # Runs every 3 hours during daytime hours PT (converted to UTC)
    - cron: '0 15,18,21,0 * * *'  # 8 AM, 11 AM, 2 PM, 5 PM PT
  workflow_dispatch:
    inputs:
      force:
        description: 'Force posting regardless of time constraints'
        required: false
        default: 'false'
        type: choice
        options:
          - 'false'
          - 'true'

jobs:
  post_news:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Set up AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run news fetch and tweet
        env:
          DODGERS_TWITTER_API_KEY: ${{ secrets.DODGERS_TWITTER_API_KEY }}
          DODGERS_TWITTER_API_SECRET: ${{ secrets.DODGERS_TWITTER_API_SECRET }}
          DODGERS_TWITTER_ACCESS_TOKEN: ${{ secrets.DODGERS_TWITTER_API_ACCESS_TOKEN }}
          DODGERS_TWITTER_ACCESS_SECRET: ${{ secrets.DODGERS_TWITTER_API_ACCESS_SECRET }}
        run: |
          if [ "${{ github.event.inputs.force }}" = "true" ]; then
            python scripts/24_fetch_news.py --post-tweet --force
          else
            python scripts/24_fetch_news.py --post-tweet
          fi 