name: Tweet Lineup

on:
  schedule:
    # Runs hourly between 10am and 6pm PST (18:00-02:00 UTC)
    - cron: '0 18-23,0-2 * * *'
  workflow_dispatch:

jobs:
  tweet_lineup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Set up AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-1

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run lineup check and tweet
      env:
        DODGERS_TWITTER_API_KEY: ${{ secrets.DODGERS_TWITTER_API_KEY }}
        DODGERS_TWITTER_API_SECRET: ${{ secrets.DODGERS_TWITTER_API_SECRET }}
        DODGERS_TWITTER_API_BEARER: ${{ secrets.DODGERS_TWITTER_API_BEARER }}
        DODGERS_TWITTER_API_ACCESS_TOKEN: ${{ secrets.DODGERS_TWITTER_API_ACCESS_TOKEN }}
        DODGERS_TWITTER_API_ACCESS_SECRET: ${{ secrets.DODGERS_TWITTER_API_ACCESS_SECRET }}
      run: python scripts/17_fetch_lineup.py --post-tweet 