name: Tweet Lineup

on:
  schedule:
    # Runs hourly, but the job will only proceed between 10am and 6pm PT.
    - cron: '0 17-23,0-2 * * *'
  workflow_dispatch:

jobs:
  tweet_lineup:
    runs-on: ubuntu-latest
    steps:
    - name: Check Time in Los Angeles
      id: time_check
      run: |
        if [[ $(TZ="America/Los_Angeles" date +'%H') -ge 8 && $(TZ="America/Los_Angeles" date +'%H') -lt 18 ]]; then
          echo "Proceeding, it's between 8am and 6pm PT."
          echo "proceed=true" >> $GITHUB_OUTPUT
        else
          echo "Stopping, it's outside of 8am-6pm PT."
          echo "proceed=false" >> $GITHUB_OUTPUT
        fi

    - uses: actions/checkout@v2
      if: steps.time_check.outputs.proceed == 'true'

    - name: Set up Python
      if: steps.time_check.outputs.proceed == 'true'
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Set up AWS Credentials
      if: steps.time_check.outputs.proceed == 'true'
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-1

    - name: Install dependencies
      if: steps.time_check.outputs.proceed == 'true'
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run lineup check and tweet
      if: steps.time_check.outputs.proceed == 'true'
      env:
          DODGERS_TWITTER_API_KEY: ${{ secrets.DODGERS_TWITTER_API_KEY }}
          DODGERS_TWITTER_API_SECRET: ${{ secrets.DODGERS_TWITTER_API_SECRET }}
          DODGERS_TWITTER_TOKEN: ${{ secrets.DODGERS_TWITTER_TOKEN }}
          DODGERS_TWITTER_TOKEN_SECRET: ${{ secrets.DODGERS_TWITTER_TOKEN_SECRET }}
      run: python scripts/17_fetch_lineup.py --post-tweet 